name: Mapping Container Tag
on:
  push:
    tags:
      # This is a regular expression
      # that matches tags like "service-v1.2.3"
      - "*"

jobs:
  echo-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Echo the tag
        run: |
          echo "The tag is ${{ github.ref }}"
          echo "commitId is ${{ github.sha }}"
